site_name: Nerds Playing PnP - Docs
theme: 
  name: material
  features:
  - navigation.instant
  logo: assets/die.png
  favicon: assets/diex64.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: indigo
      accent: deep purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: indigo